### ISSUE TITLE
Approved drugs potency not shown

### ISSUE THREAD

**Issue by southalln** [ncats/pharos_frontend#5]
https://pharos.ncats.nih.gov/targets/P30531

The potency of the approved drug is not shown in the drug panel.
https://pharos.ncats.nih.gov/ligands/207857

Potencies are shown in the active ligands panel, but the entries (60 cmpds) are not sorted by potency (which seems wierd, unless the ligands are sorted by development phase).

**Comment by tsheils** [comment]
This was fixed with newest redesign
